In [1]:
import pandas as pd
import joblib

In [2]:
model = joblib.load("models/final_model.pkl")
scaler = joblib.load("models/scaler.pkl")

In [4]:
df = pd.read_csv("csv//processed_data.csv")

customer = df.drop("Churn", axis=1).iloc[[0]]

In [5]:
customer

,tenure,MonthlyCharges,TotalCharges,gender_Male,SeniorCitizen_Yes,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,TenureGroup_49-60,TenureGroup_61-72,TotalChargesGroup_1001-2000,TotalChargesGroup_2001-3000,TotalChargesGroup_3001-4000,TotalChargesGroup_4001-5000,TotalChargesGroup_5001-6000,TotalChargesGroup_6001-7000,TotalChargesGroup_7001-8000,TotalChargesGroup_8001-9000
0,1,29.85,29.85,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False

In [6]:
customer_scaled = scaler.transform(customer)

prediction = model.predict(customer_scaled)

probability = model.predict_proba(customer_scaled)

In [7]:
print("Prediction:", prediction[0])

print("Probability of No Churn :", probability[0][0])
print("Probability of Churn    :", probability[0][1])

Prediction: 1
Probability of No Churn : 0.3608872489922591
Probability of Churn    : 0.6391127510077409

In [8]:
customers = df.drop("Churn", axis=1).head(10)

customers_scaled = scaler.transform(customers)

predictions = model.predict(customers_scaled)

customers["Prediction"] = predictions

customers

,tenure,MonthlyCharges,TotalCharges,gender_Male,SeniorCitizen_Yes,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,TenureGroup_61-72,TotalChargesGroup_1001-2000,TotalChargesGroup_2001-3000,TotalChargesGroup_3001-4000,TotalChargesGroup_4001-5000,TotalChargesGroup_5001-6000,TotalChargesGroup_6001-7000,TotalChargesGroup_7001-8000,TotalChargesGroup_8001-9000,Prediction
0,1,29.85,29.85,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,1
1,34,56.95,1889.50,True,False,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,0
2,2,53.85,108.15,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,0
3,45,42.30,1840.75,True,False,False,False,False,True,False,...,False,True,False,False,False,False,False,False,False,0
4,2,70.70,151.65,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,1
5,8,99.65,820.50,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,False,1
6,22,89.10,1949.40,True,False,False,True,True,False,True,...,False,True,False,False,False,False,False,False,False,0
7,10,29.75,301.90,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,0
8,28,104.80,3046.05,False,False,True,False,True,False,True,...,False,False,False,True,False,False,False,False,False,1
9,62,56.15,3487.95,True,False,False,True,True,False,False,...,True,False,False,True,False,False,False,False,False,0

In [9]:
customers["Churn Probability"] = model.predict_proba(customers_scaled)[:,1]

customers.head()

,tenure,MonthlyCharges,TotalCharges,gender_Male,SeniorCitizen_Yes,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,TotalChargesGroup_1001-2000,TotalChargesGroup_2001-3000,TotalChargesGroup_3001-4000,TotalChargesGroup_4001-5000,TotalChargesGroup_5001-6000,TotalChargesGroup_6001-7000,TotalChargesGroup_7001-8000,TotalChargesGroup_8001-9000,Prediction,Churn Probability
0,1,29.85,29.85,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,1,0.639113
1,34,56.95,1889.50,True,False,False,False,True,False,False,...,True,False,False,False,False,False,False,False,0,0.019744
2,2,53.85,108.15,True,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,0,0.337605
3,45,42.30,1840.75,True,False,False,False,False,True,False,...,True,False,False,False,False,False,False,False,0,0.030797
4,2,70.70,151.65,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,1,0.737318